CREATE TABLE NIVELES(
    ID_NIVEL INT,
    NOMBRE VARCHAR(50),
CONSTRAINT PK_ID_NIVEL PRIMARY KEY(ID_NIVEL)
);

INSERT INTO NIVELES VALUES(1, 'ADMINISTRADOR');
INSERT INTO NIVELES VALUES(2, 'SUPERVISOR');
INSERT INTO NIVELES VALUES(3, 'TRABAJADOR');

CREATE TABLE USUARIOS(
  ID_USER INT,
  USER_NAME VARCHAR(10),
  PASS VARCHAR(10),
  NIVEL INT,
CONSTRAINT PK_ID_USER PRIMARY KEY(ID_USER),
CONSTRAINT FK_ID_NIVEL FOREIGN KEY(NIVEL) REFERENCES NIVELES(ID_NIVEL)
);

INSERT INTO USUARIOS VALUES(1234, 'JA', 'JA', 1);
INSERT INTO USUARIOS VALUES(1235, 'MA', 'MA', 2);
INSERT INTO USUARIOS VALUES(1236, 'PA', 'PA', 3);